# github에서 workflows를 root로 인식한다.
# ------------------------------------------------------
# name키를 생략하면 파일경로가 workflows이름으로 사용되므로,
# 필수 지정은 아니지만 이름 사용을 권장한다.
# 하나의 workflows에는 여러 개의 워크플로우 사용이 가능하다.

# on : 워크플로우가 언제 실행되는지 설정. push 이벤트를 가장 선호함

# 워크플로우는 수동으로 실행할 수 있지만
# 일반적으로 코드저장소에 어떤 이벤트가 발생할 때마다
# 워크플로우를 자동으로 트리거하는 경우가 대부분이다.

# name: Our First Workflow
# on: push

# 위와 같이 설정해두면 누군가가 코드저장소에 변경사항을 push하거나
# full request가 merge되면, 이 워크플로우가 자동으로 실행되게 된다.

name: Our First Workflow
on: push
